sudo: false          # 开启基于容器的Travis CI任务，让编译效率更高。
language: node_js    # 声明构建语言环境
node_js:
    - "6"
    - "node"
os:
  - osx

notifications:       # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置false吧
    email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - zip
      - libgtk2.0-0

before_install:
    - npm install

script:              # 执行:下面的命令
    - npm run app